### ISSUE TITLE
Reading the parsing file

### ISSUE THREAD

**Issue by Juanjdurillo** [IBM/Graph2Tree#4]
Hi there! Thanks for making the software available. After reading the phenomenal paper, I was interesting in the code and set to do some experiments, but I am having troubles in making it run (maybe simply my misunderstanding.)

Running the train.sh fails for me  at https://github.com/IBM/Graph2Tree/blob/04e5b96134816037aa0dfb41e39fa4f9d60f099d/src/graph2tree.py#L337 as the file map.pkl is not found. Using the file file_for_parsing.pkl which is the only pkl file in the repo, I get the following error though:
   ```
 word_manager, form_manager = managers
ValueError: too many values to unpack (expected 2)
```
I am sure I am missing something here (should I generate the map.pkl in a different way?) It would really great if you could help me out :). Thanks!

**Comment by schenglee** [comment]
Hi juanjo,

maybe you should run the graph construction scripts first to generate the file `map.pkl`: [constituency.py](https://github.com/IBM/Graph2Tree/blob/master/data/GraphConstruction/constituency.py#L470-L472).

Hope this can help you.

**Comment by Juanjdurillo** [comment]
Hi! Thanks as lot! It does help a lot :). I am not sure why it did not run before (as is part of the train.sh script)...
