### ISSUE TITLE
Graph2Tree with custom dataset

### ISSUE THREAD

**Issue by maurovit** [IBM/Graph2Tree#5]
Hello,
I trained your model with dataset that you provided, now I want to train the model with a custom dataset, which aim is semantic parsing. How can I do that? If i run constituency.py without file_for_parsing.plk i get an error:
`Name Error: preparsed_file is not defined`
in featureExtract of InputPreprocessor class.
Can you help me?

**Comment by teddylfwu** [comment]
Dear Mauro,

Please see our new graph4nlp library, which have implemented
graph2tree model.

https://github.com/graph4ai/graph4nlp


Yours sincerely,

Lingfei (Teddy) Wu
Principal Scientist
JD.COM Silicon Valley Research Center,
675 E Middlefield Rd, Mountain View, CA 94043
Phone: +1 757-634-5455
Email: ***@***.***, ***@***.***
Web: https://sites.google.com/a/email.wm.edu/teddy-lfwu/

**Comment by teddylfwu** [comment]
Dear All,

Please see our newly released graph4nlp library: https://github.com/graph4ai/graph4nlp, which have implemented many GNN methods like Graph2Seq and Graph2Tree models.

**Comment by maurovit** [comment]
Thank you for your reply, great work.
